version: 2
jobs:
  build:
    working_directory: ~/angular-slickgrid
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      - restore_cache:
          key: angular-slickgrid-build-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - run: yarn install --frozen-lockfile
      - run:
          name: Install Jest JUnit coverage reporter
          command: yarn add --dev jest-junit
      - save_cache:
          key: angular-slickgrid-build-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run:
          name: Run Jest tests with JUnit as reporter
          command: ./node_modules/.bin/jest --config test/jest.config.js --ci --runInBand --collectCoverage=true --reporters=default --reporters=jest-junit
          environment:
            JEST_JUNIT_OUTPUT: "reports/junit/js-test-results.xml"
      - run:
          name: Upload Jest coverage to Codecov
          command: bash <(curl -s https://codecov.io/bash) -t ${CODECOV_TOKEN}
      - run:
          name: Start Dev WebServer
          command: yarn start
          background: true
      - restore_cache:
          name: Restoring Cache for Cypress
          keys:
            - e2e-tests-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - run:
          name: Installing Cypress dependencies
          command: |
            cd test/cypress
            yarn install --frozen-lockfile
      - save_cache:
          name: Saving Cache for Cypress
          key: e2e-tests-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run:
          name: Running Cypress E2E tests with JUnit reporter
          command: |
            cd test/cypress
            yarn cypress:ci:mochawesome
      - store_test_results:
          path: reports/junit
      - store_artifacts:
          path: reports/junit
